modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://github.com/itsmeow/BaseMod/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/basemod"
logoFile="icon.png"
credits="itsmeow for Programming"
authors="itsmeow"
license="MIT"
[[mods]]
modId="basemod"
version="${file.jarVersion}"
displayName="BaseMod"
description='''
A base mod.'''
[[dependencies.basemod]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"