name: 'Build PR'
on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.github/**'
      - '.gitignore'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - { uses: actions/checkout@v2, with: { fetch-depth: 0 } }
      - { name: 'Set up JDK 17', uses: actions/setup-java@v2, with: { distribution: 'adopt', java-version: '17' } }
      - { name: Build with Gradle, id: build, env: { USE_ALPHAS: false }, run: 'chmod +x gradlew && ./gradlew build' }